// Generated by scripts/fetch-merch.mjs — do not edit by hand.
// Run `node scripts/fetch-merch.mjs` to regenerate.

export interface MerchProduct {
  slug: string;
  name: string;
  price: number;
  category: string;
  desc: string;
  image: string;
  url: string;
}

export const MERCH_PRODUCTS: MerchProduct[] = [
  {
    "slug": "die-cut-stickers",
    "name": "Die-cut stickers",
    "price": 5,
    "category": "Stickers",
    "desc": "Premium die-cut vinyl stickers with Surf Vikings graphics. Weatherproof and ready to stick anywhere.",
    "image": "/merch/die-cut-stickers.webp",
    "url": "https://surfvikings.printful.me/product/die-cut-stickers"
  },
  {
    "slug": "youth-tee",
    "name": "Youth Short Sleeve T-Shirt",
    "price": 17.49,
    "category": "Apparel",
    "desc": "Viking-branded tee sized for young warriors. Soft, durable, and ready for adventure.",
    "image": "/merch/youth-tee.webp",
    "url": "https://surfvikings.printful.me/product/youth-short-sleeve-t-shirt"
  },
  {
    "slug": "water-bottle-straw",
    "name": "Stainless steel water bottle with a straw lid",
    "price": 28,
    "category": "Accessories",
    "desc": "Stainless steel water bottle with convenient straw lid. Viking-branded hydration for on-the-go.",
    "image": "/merch/water-bottle-straw.webp",
    "url": "https://surfvikings.printful.me/product/stainless-steel-water-bottle-with-a-straw-lid"
  },
  {
    "slug": "youth-long-sleeve",
    "name": "Youth long sleeve tee",
    "price": 22,
    "category": "Apparel",
    "desc": "Long sleeve tee for young Vikings. Extra coverage for cooler mornings and after-surf sessions.",
    "image": "/merch/youth-long-sleeve.webp",
    "url": "https://surfvikings.printful.me/product/youth-long-sleeve-tee"
  },
  {
    "slug": "corduroy-cap",
    "name": "Vintage corduroy cap",
    "price": 19.5,
    "category": "Headwear",
    "desc": "Textured corduroy cap with vintage appeal and embroidered Surf Vikings wave logo.",
    "image": "/merch/corduroy-cap.webp",
    "url": "https://surfvikings.printful.me/product/vintage-corduroy-cap"
  },
  {
    "slug": "heavyweight-tee",
    "name": "Men’s premium heavyweight tee",
    "price": 20.5,
    "category": "Apparel",
    "desc": "Heavyweight premium tee with Surf Vikings wave logo. Thick, soft, and built to last.",
    "image": "/merch/heavyweight-tee.webp",
    "url": "https://surfvikings.printful.me/product/mens-premium-heavyweight-tee"
  },
  {
    "slug": "kiss-cut-decals",
    "name": "Kiss-cut vinyl decals",
    "price": 2,
    "category": "Stickers",
    "desc": "Precision kiss-cut decals with the Surf Vikings wave logo. Perfect for smooth surfaces.",
    "image": "/merch/kiss-cut-decals.webp",
    "url": "https://surfvikings.printful.me/product/kiss-cut-vinyl-decals"
  },
  {
    "slug": "bubble-free-stickers",
    "name": "Bubble-free stickers",
    "price": 3,
    "category": "Stickers",
    "desc": "Premium bubble-free vinyl stickers with Surf Vikings graphics. Smooth application, clean finish.",
    "image": "/merch/bubble-free-stickers.webp",
    "url": "https://surfvikings.printful.me/product/bubble-free-stickers"
  },
  {
    "slug": "unisex-tee",
    "name": "Unisex t-shirt",
    "price": 19,
    "category": "Apparel",
    "desc": "Everyday unisex tee with bold Surf Vikings graphics. Soft and comfortable for all-day wear.",
    "image": "/merch/unisex-tee.webp",
    "url": "https://surfvikings.printful.me/product/unisex-t-shirt"
  },
  {
    "slug": "dad-hat",
    "name": "Dad hat",
    "price": 19,
    "category": "Headwear",
    "desc": "Relaxed-fit dad hat with embroidered Surf Vikings logo. Low profile and easy to wear all day.",
    "image": "/merch/dad-hat.webp",
    "url": "https://surfvikings.printful.me/product/dad-hat"
  },
  {
    "slug": "sticker-sheet",
    "name": "Sticker sheet",
    "price": 9.5,
    "category": "Stickers",
    "desc": "Sheet of assorted Surf Vikings stickers. Multiple designs to deck out your board, laptop, or water bottle.",
    "image": "/merch/sticker-sheet.webp",
    "url": "https://surfvikings.printful.me/product/sticker-sheet"
  },
  {
    "slug": "holographic-stickers",
    "name": "Holographic stickers",
    "price": 5.5,
    "category": "Stickers",
    "desc": "Eye-catching holographic stickers that shift color in the light. Stand out from the lineup.",
    "image": "/merch/holographic-stickers.webp",
    "url": "https://surfvikings.printful.me/product/holographic-stickers"
  },
  {
    "slug": "og-tee",
    "name": "Surf Vikings T-Shirt",
    "price": 14.5,
    "category": "Apparel",
    "desc": "The original Surf Vikings tee. Comfortable, durable, and unmistakably Viking.",
    "image": "/merch/og-tee.webp",
    "url": "https://surfvikings.printful.me/product/surf-vikings-t-shirt"
  },
  {
    "slug": "beach-towel",
    "name": "Towel",
    "price": 37.5,
    "category": "Beach",
    "desc": "All-over sublimation beach towel with bold Viking graphics. Soft cotton blend that dries fast.",
    "image": "/merch/beach-towel.webp",
    "url": "https://surfvikings.printful.me/product/towel"
  },
  {
    "slug": "foam-trucker",
    "name": "Foam trucker hat",
    "price": 16,
    "category": "Headwear",
    "desc": "Retro foam trucker hat with mesh back and bold Surf Vikings wave graphic. Breathable and fun.",
    "image": "/merch/foam-trucker.webp",
    "url": "https://surfvikings.printful.me/product/foam-trucker-hat"
  },
  {
    "slug": "patches",
    "name": "Embroidered patches",
    "price": 12,
    "category": "Accessories",
    "desc": "Premium embroidered patches to customize your gear with authentic Viking designs.",
    "image": "/merch/patches.webp",
    "url": "https://surfvikings.printful.me/product/embroidered-patches"
  },
  {
    "slug": "twill-cap",
    "name": "Vintage Cotton Twill Cap",
    "price": 20.5,
    "category": "Headwear",
    "desc": "Washed cotton twill cap with that broken-in vintage look. Embroidered Surf Vikings logo.",
    "image": "/merch/twill-cap.webp",
    "url": "https://surfvikings.printful.me/product/vintage-cotton-twill-cap"
  },
  {
    "slug": "ringer-tee",
    "name": "Unisex ringer t-shirt",
    "price": 25,
    "category": "Apparel",
    "desc": "Classic ringer tee with retro contrast trim and Surf Vikings design. Vintage vibes, modern comfort.",
    "image": "/merch/ringer-tee.webp",
    "url": "https://surfvikings.printful.me/product/unisex-ringer-t-shirt"
  },
  {
    "slug": "premium-hoodie",
    "name": "Unisex premium mid-weight hoodie",
    "price": 30.5,
    "category": "Apparel",
    "desc": "Modern mid-weight hoodie with Surf Vikings branding. Premium cotton blend built for layering after dawn patrol.",
    "image": "/merch/premium-hoodie.webp",
    "url": "https://surfvikings.printful.me/product/unisex-premium-mid-weight-hoodie"
  },
  {
    "slug": "water-bottle",
    "name": "Stainless steel water bottle",
    "price": 26.5,
    "category": "Accessories",
    "desc": "Insulated water bottle with Surf Vikings branding. Keeps drinks cold through the longest sessions.",
    "image": "/merch/water-bottle.webp",
    "url": "https://surfvikings.printful.me/product/stainless-steel-water-bottle"
  },
  {
    "slug": "under-armour-dad-hat",
    "name": "Under Armour® dad hat",
    "price": 32,
    "category": "Headwear",
    "desc": "Premium dad hat by Under Armour with Surf Vikings embroidery. Moisture-wicking performance fit.",
    "image": "/merch/under-armour-dad-hat.webp",
    "url": "https://surfvikings.printful.me/product/under-armour-dad-hat"
  },
  {
    "slug": "snapback",
    "name": "Snapback Hat",
    "price": 22,
    "category": "Headwear",
    "desc": "Classic snapback with embroidered Surf Vikings logo. Structured crown and flat brim for that clean look.",
    "image": "/merch/snapback.webp",
    "url": "https://surfvikings.printful.me/product/snapback-hat"
  },
  {
    "slug": "mens-rash-guard",
    "name": "Men's Rash Guard",
    "price": 55,
    "category": "Surf Gear",
    "desc": "High-performance rash guard with all-over Surf Vikings print. UV protection and 4-way stretch for serious sessions.",
    "image": "/merch/mens-rash-guard.webp",
    "url": "https://surfvikings.printful.me/product/mens-rash-guard"
  }
];
